# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-02-20 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='image',
            field=models.ImageField(max_length=200, upload_to='uploads/cities/'),
        ),
        migrations.AlterField(
            model_name='country',
            name='image',
            field=models.ImageField(max_length=200, upload_to='uploads/countries/'),
        ),
    ]
