# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-02-21 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0003_hotel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sight',
            name='description',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='sight',
            name='image',
            field=models.ImageField(default=None, max_length=200, upload_to='uploads/sights/'),
        ),
    ]
