# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-02-21 22:07
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarReservationRequest',
            fields=[
                ('car_requested', models.AutoField(primary_key=True, serialize=False)),
                ('pick_up_date', models.DateField(default=datetime.date.today)),
                ('Drop_off_date', models.DateField(default=datetime.date.today)),
                ('pick_up_time', models.TimeField(default='00:00')),
                ('Drop_off_time', models.TimeField(default='00:00')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
