# -*- coding: utf-8 -*-
<<<<<<< HEAD
# Generated by Django 1.11.11 on 2019-02-20 18:06
=======
<<<<<<< HEAD
# Generated by Django 1.11.15 on 2019-02-19 17:13
=======
# Generated by Django 1.11.11 on 2019-02-20 11:46
>>>>>>> 792b699494b4874dfdef31580113304f4183a3bc
>>>>>>> de066d912e410e57a347c473e3f7d83ca60a2cfe
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import user_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, upload_to=user_app.models.pics_directory_path)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
