# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-19 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='user_username',
            field=models.CharField(default='null', max_length=40),
        ),
    ]
